from Tactics.tactic import Tactic
from Tactics.punish import Punish
from Tactics.defend import Defend
from Tactics.approach import Approach
from Tactics.keepdistance import KeepDistance
from Tactics.pressure import Pressure
from Tactics.wait import Wait
from Tactics.recover import Recover
from Tactics.mitigate import Mitigate
from Tactics.edgeguard import Edgeguard
from Tactics.infinite import Infinite
from Tactics.celebrate import Celebrate
from Tactics.retreat import Retreat
from Tactics.selfdestruct import SelfDestruct
